config/routes.rb
Myapp::Application.routes.draw do

  devise_for :users

  get "staticpages/index"

  root :to => 'staticpages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
  attr_accessible :emotion, :hour, :learned, :image
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :gender
  # attr_accessible :title, :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_filter :authenticate_user!
 
def index
	@pics = current_user.pics.all
end


 def new
 	 @pic = Pic.new
 end

def create
		@pic = current_user.pics.build(params[:pic])
		@pic.save
		redirect_to pics_path
	end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
<div class="navbar-inner">
<div class="container">

  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </a>

  <!-- Be sure to leave the brand out there if you want it shown -->
        <%= link_to "Home", root_path, :class => 'brand' %>
  <ul class ="nav">
				
        <li><%= link_to "All Pics", pics_path %></li>
        <li><%= link_to "New Pic", new_pic_path %></li>

				
				</ul>
<ul class="nav pull-right">
  <% if current_user.present? %>
          <li>
              <%= link_to current_user.email, edit_user_registration_path %>
          </li>
          <li>
              <%= link_to 'Sign Out',destroy_user_session_path,:method =>:delete %>
          </li>
            <% else %>
         
            <li>
                <%= link_to 'Sign In',new_user_session_path %>
            </li>
            <li>
                <%= link_to 'Sign Up',new_user_registration_path %>
            </li>
            <% end -%>
          </ul>


  <!-- Everything you want hidden at 940px or less, place within here -->
  <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
  </div>

</div>
</div>
</div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<div class = "custom-title">
	<h1 class="custom-font1"> My Pics </h1>
</div>

<% current_user.pics.each do |pic| %>
	<div class= "my-wrapper span3">
		<h2>
				Hour <%= pic.hour %>
		</h2>

		<h3>
			I feel <%= pic.emotion %>
		</h3>

		<p>
			I learned that <%= pic.learned %>
		</p>
	<div >
			<%= image_tag pic.image %>

		</div>

	</div>


<% end %>

app/views/pics/new.html.erb
<div class = "custom-title text-center">
	<h1 class="custom-font3">Upload Your Pic</h1>
	<%= current_user.email %>
</div>

<div class = "my-wrapper2 span4 offset5 text-center">
	<%= simple_form_for @pic  do |f| %>
	<%= f.input :hour,label: 'Which hour?', label_html: { class: 'custom-font-form' } %>
	<%= f.input :image, as: :file, label_html: { class: 'custom-font-form' } %>
	<%= f.input :emotion,label: 'how you feelin`', label_html: { class: 'custom-font-form' }%>
	<%= f.input :learned,label: 'Whatch you learnin`', label_html: { class: 'custom-font-form' } %>
	<%= submit_tag "Save", class: 'btn btn-large btn-warning' %>
<% end %>	
</div>

app/views/staticpages/index.html.erb
<!-- <h1>Sny-door</h1>
<p> What's up baby?</p> -->
<div class ="span5 offset8 text-center stolen-surfbox">

	<h1 class ="custom-font1 custom-h1"> Hello I'm Pratik! </h1>
	<br/>
	<h2 class ="custom-font2"> I'm having a lot of fun remaking the Firehose App</h2>
	<br/>
	<%= link_to "Launch App", new_pic_path, :class =>'btn btn-large btn-warning' %>


</div>